#!/bin/bash

selected=$(fd -t d --min-depth 1 --max-depth 1 . "$HOME" "$HOME/Studia" "$HOME/Projects" "$HOME/Projekty" 2>/dev/null | fzf)

if [[ -z "$selected" ]]; then
	exit 0
fi

selected_name=$(basename "$selected" | tr ':., ' '____')

switch_to() {
	if [[ -z "$TMUX" ]]; then
		tmux attach-session -t $selected_name
	else
		tmux switch-client -t $selected_name
	fi
}

if tmux has-session -t=$selected_name 2>/dev/null; then
	switch_to
	exit 0
fi

tmux new-session -ds $selected_name -c $selected -n main

tmux send-keys -t $selected_name:1 "ready-tmux-glob" Enter

sleep 0.3

switch_to
