version: 1
git_protocol: ssh
editor: nvim
prompt: enabled
prefer_editor_prompt: disabled
pager: less
aliases:
  co: pr checkout
  st: status
  rp: repo
  is: issue
  web: browse
http_unix_socket:
browser: firefox
color_labels: enabled
accessible_colors: disabled
accessible_prompter: disabled
spinner: disabled
