#!/usr/bin/env bash

echo "Welcome to the KWin installation script!"
echo "Installing KWin scripts..."

kpackagetool6 --type KWin/Script --install ../local/kwin/* &>/dev/null

echo "Successfully installed all KWin scripts!"

echo "Opening systems settings page to manually enable the KWin scripts now..."

(systemsettings kcm_kwin_scripts &>/dev/null && sleep 3)

echo "Opening systems settings page to manually import the KDE shortcuts scheme from the diy/kde directory..."

(systemsettings kcm_keys &>/dev/null)

YELLOW='\033[0;33m'
RESET='\033[0m'

echo
echo -e "${YELLOW}[WARNING]${RESET}: This script is NOT idempotent!"
echo -e "${YELLOW}[WARNING]${RESET}: It is highly advised you check that the KWin scripts have correctly enabled keybindings!"
echo

echo "Thank you for running this script! Exiting..."
