#!/usr/bin/env bash

echo "Welcome to the perms script!"
echo "Changing permissions on vital scripts..."

chmod +x local/scripts/*
chmod +x .ready-tmux

echo "All vital scripts are now executable! Exiting..."
