#!/usr/bin/env bash

echo "Welcome to the stow script!"
echo "Changing permissions on vital scripts and dirs..."

chmod +x local/scripts/*
chmod +x programs/home/.ready-tmux
chmod 700 programs/home/.ssh
chmod 700 programs/home/.ssh/sockets

[[ -f programs/home/.ssh/config ]] && chmod 600 programs/home/.ssh/config

find programs/home/.ssh -type f -name 'id_*' ! -name '*.pub' -exec chmod 600 {} \;
find programs/home/.ssh -type f -name '*.pub' -exec chmod 644 {} \;

[[ -d programs/home/.gnupg ]] && chmod 700 programs/home/.gnupg
[[ -f programs/home/.gnupg/gpg-agent.conf ]] && chmod 600 programs/home/.gnupg/gpg-agent.conf

echo "All vital scripts and dirs now have good perms! Continuing..."

script_dir="$(cd $(dirname "${BASH_SOURCE[0]}") && cd .. && pwd)"
echo "Trying to stow for ${script_dir}..."

for path in "${conflicting_paths[@]}"; do
	remove_if_not_symlink "$path"
done

echo "Stowing dotfiles from $script_dir..."
cd "$script_dir/programs"

stow --restow -t "$HOME/.config" config
stow --restow -t "$HOME" home

YELLOW='\033[0;33m'
RESET='\033[0m'

echo
echo -e "${YELLOW}[WARNING]${RESET}: This script is NOT idempotent, and might fail!"
echo -e "${YELLOW}[WARNING]${RESET}: It is highly advised you check the above errors (if any),"
echo -e "${YELLOW}[WARNING]${RESET}: and whether you have stale symlinks from previous runs/builds, or old distro unlinked files!"
echo

echo "Stow completed! Exiting..."
