#!/usr/bin/env bash

echo "Welcome to TPM installation script!"

TPM_DIR="$HOME/.tmux/plugins/tpm"

if [[ -d "$TPM_DIR" ]]; then
  echo "TPM already installed at $TPM_DIR! Exiting..."
  exit 0
fi

echo "Installing TPM..."
git clone https://github.com/tmux-plugins/tpm "$TPM_DIR"
echo "TPM installed successfully! Exiting..."
