# What protocol to use when performing Git operations. Supported values: ssh, https.
git_protocol: ssh
# What editor glab should run when creating issues, merge requests, etc. This global config cannot be overridden by hostname.
editor:
# What browser glab should run when opening links. This global config cannot be overridden by hostname.
browser:
# Set your desired Markdown renderer style. Available options are [dark, light, notty]. To set a custom style, refer to https://github.com/charmbracelet/glamour#styles
glamour_style: dark
# Allow glab to automatically check for updates and notify you when there are new updates.
check_update: false
# Last update check timestamp, used for checking when the last update check was performed.
last_update_check_timestamp:
# Whether or not to display hyperlink escape characters when listing items like issues or merge requests. Set to TRUE to display hyperlinks in TTYs only. Force hyperlinks by setting FORCE_HYPERLINKS=1 as an environment variable.
display_hyperlinks: false
# Default GitLab hostname to use.
host: gitlab.com
# Set to true (1) to disable prompts, or false (0) to enable them.
no_prompt: false
# Set to false (0) to disable sending usage data to your GitLab instance or true (1) to enable.
# See https://docs.gitlab.com/administration/settings/usage_statistics/
# for more information
telemetry: true
# Configuration specific for GitLab instances.
hosts:
    gitlab.com:
        # What protocol to use to access the API endpoint. Supported values: http, https.
        api_protocol: https
        # Configure host for API endpoint. Defaults to the host itself.
        api_host: gitlab.com
        # Your GitLab access token. To get one, read https://docs.gitlab.com/user/profile/personal_access_tokens/
        token: 8e413453761da867c809b6ac704f66cc36a405680bfc20bca16bce4b0a41a0d1
        # The domains of associated container registries. These are used to configure the
        # Docker credential helper.
        container_registry_domains: gitlab.com,gitlab.com:443,registry.gitlab.com
        is_oauth2: "true"
        oauth2_refresh_token: 62a48f4d00b559d316fca66d938ef2906b9361bc85abec1383f6417a6d086d4d
        oauth2_expiry_date: 10 Aug 25 14:29 CEST
        git_protocol: ssh
        user: Eden1111
