[window]
decorations = "none"
startup_mode = "Maximized"

[colors.primary]
background = "#000000"

[font]
normal = { family = "0xProto Nerd Font Mono", style = "normal" }

[cursor]
style.blinking = "Always"
